### ISSUE TITLE
Adjust BEVFusion model to output BEV of 3D Object Detection

### ISSUE THREAD

**Issue by nlitz88** [nlitz88/BEVFusion-ROS-TensorRT#2]
Per the output I got here: https://github.com/nlitz88/workzone/issues/15#issuecomment-2063172615

Basically, the model is currently outputting a visualization of the 3D object detection task, but not from the perspective that we want. We want the BEV of the 3D object detections--so we will likely have to spend a bit of time diving into the model's configuration to figure that out.

**Comment by CMUBOB97** [comment]
Okay a note for myself or anyone interested in the "surgery":

The result image stitching occurs in visualize function call at [bevfusion_plugin.cpp](https://github.com/nlitz88/BEVFusion-ROS-TensorRT/blob/2-adjust-bevfusion-model-to-output-bev-of-3d-object-detection/src_plugin/bevfusion_plugin.cpp#L261)

The bev prediction drawing part is there, easy to kick out other input images. However, it is drawing as a 3D BEV instead of 2D. I need to investigate more on that.

**Comment by CMUBOB97** [comment]
Okay my understanding of the "surgery":
- To remove input camera images, remove line 104 to 145 in visualize function.
- To get the 2D BEV, modify draw_prediction function in [visualize.cu](https://github.com/nlitz88/BEVFusion-ROS-TensorRT/blob/main/src/common/visualize.cu#L356).

The tricky part is, will it be quicker to find the 2D BEV generation code and just swap it, or go ahead and modify this 3D BEV function. @nlitz88 I need your wisdom to make the judgement.

**Comment by nlitz88** [comment]
> will it be quicker to find the 2D BEV generation code

This _could_ be true--but when you say 2D BEV generation code, do you mean like the code they are using to generate the _semantic segmentation_ costmap looking thing? Or are you talking about trying to find where the BEV projection of the 3D OD would have been created somewhere in their implementation?

If you _are_ talking about finding the code for the BEV projection of the 3D OD--I guess we are assuming this exists because that is what the visualization gave us when we were playing around with the original repo, right? I suppose there is a possibility that this view doesn't doesn't natively exist--maybe that was only a visualization view? Just thinking through the worst case scenario--I'm not sure of that at all.

**Comment by CMUBOB97** [comment]
Yea maybe they have their own visualization script in the original repo for BEV projection pic (which is what we worked on). Again, if that is the case, then we can just take their implementation as a reference, and put it in draw_prediction.

Maybe that doesn't seem to be too hard...

**Comment by CMUBOB97** [comment]
@nlitz88 A few things:

1. I was in the wrong branch before when finding the reference of `visualize` function. In galactic branch (the one you created), it was in src_plugin/bevfusion_plugin.cpp.

2. I have pushed some changes in the branch. Did some translation in the code comments. It should only render 3D bboxes in ego frame. Could you test it out for me?

Once it works, lmk and I will proceed with changing `draw_prediction` (my final decision). It has some math which I think I understand. Still, there is a chance that I will get nuked.

**Comment by nlitz88** [comment]
![image](https://github.com/nlitz88/BEVFusion-ROS-TensorRT/assets/9357423/3a5d80b8-0016-4522-9623-61797945fff7)

Cool! YES--it looks like you were able to successfully rip out those image visualizations. Very cool.

Let me know how that goes and I can give it a go. I am hoping to have some time to help out more hands on tomorrow.

**Comment by CMUBOB97** [comment]
@nlitz88 Check out the latest commit on [adjust BEVFusion branch](https://github.com/nlitz88/BEVFusion-ROS-TensorRT/commit/6497fec4ba90ee3fb99ce0a42ddedb06bab9368a)

I have made a few comments on the code to mark our approach for the "surgery". TLDR:

- We need to figure out how reference frame is defined, so that we can change the `transformation_predictions` function, which will give us the right BEV
- In `draw_prediction`, we need to modify the definition of edges, so that it only keeps 4 (i.e., 2D view)
- It will be easier if we can meet up, and change, test, and iterate. That's so far the easiest way to tackle.

Let me know what you think.

**Comment by nlitz88** [comment]
![Image](https://github.com/nlitz88/BEVFusion-ROS-TensorRT/assets/9357423/edc973b3-7e27-4eed-a47a-bd8915796c05)

- Changed the rotation angle in the `BEVArtistParameter` struct for both rotation about the X and Y axis of the LiDAR frame.
